export const BedServices = [
  {
    id: 1,
    src: "/images/categories/bed-services/category-product-1.png",
    title: "آباژور مدل طلایی 0129",
    price: "23500000",
    url: "لوستر تک شعله مدل شکوفه",
    score: 4.5,
    discount: "",
    code: 10258,
    like: 0,
    date: "2022-12-20",
    brand: "tan aram",
    stock: 250,
  },
  {
    id: 2,
    src: "/images/categories/bed-services/category-product-2.png",
    title: "تخت خواب مدل سفید",
    price: "23000000",
    url: "تخت خواب مدل سفید",
    score: 4.8,
    discount: "",
    code: 10259,
    like: 0,
    date: "2022-12-21",
    brand: "asayesh",
    stock: 0,
  },
  {
    id: 3,
    src: "/images/categories/bed-services/category-product-3.png",
    title: "تخت خواب مدل قهوه",
    price: "25000000",
    url: "تخت خواب مدل قهوه",
    score: 4.2,
    discount: "",
    code: 10260,
    like: 0,
    date: "2022-12-25",
    brand: "khoshkhab",
    stock: 300,
  },
  {
    id: 4,
    src: "/images/categories/bed-services/category-product-4.png",
    title: "تخت خواب مدل طوس",
    price: "21500000",
    url: "تخت خواب مدل طوس",
    score: 4,
    discount: "",
    code: 10261,
    like: 0,
    date: "2022-12-19",
    brand: "test",
    stock: 600,
  },
  {
    id: 5,
    src: "/images/categories/bed-services/category-product-5.png",
    title: "مبل تخت خواب شو",
    price: "21500000",
    url: "مبل تخت خواب شو",
    score: 4,
    discount: "29",
    code: 10262,
    like: 0,
    date: "2022-12-08",
    brand: "test",
    stock: 0,
  },
  {
    id: 6,
    src: "/images/categories/bed-services/category-product-6.png",
    title: "تخت خواب مدل 01",
    price: "26500000",
    url: "تخت خواب مدل 01",
    score: 4.9,
    discount: "29",
    code: 10263,
    like: 0,
    date: "2022-12-26",
    brand: "test",
    stock: 150,
  },
];
